Repository actiniumio/allspark, pull requests merged in 2018-09, with the labels that each got.

#88 Fix error docker repo file vars
  roles/system/defaults/main.yml
  roles/system/tasks/RedHat.yml
Labels: bug

#90 fix error on system playbook
  roles/system/tasks/Debian.yml
  roles/system/tasks/RedHat.yml
Labels: bug

#85 Feature/haproxy
  CONTRIBUTING.md
  Vagrantfile
  docs/nav/architecture.md
  docs/nav/configuration.md
  group_vars/all.yml
  install.yml
  roles/download/defaults/main.yml
  roles/gitlab/defaults/main.yml
  roles/gitlab/tasks/main.yml
  roles/gitlab/templates/gitlab.rb.j2
  roles/haproxy/defaults/main.yml
  roles/haproxy/tasks/certificates.yml
  roles/haproxy/tasks/main.yml
  roles/haproxy/tasks/selfsign_domain.yml
  roles/haproxy/templates/crt-list.txt.j2
  roles/haproxy/templates/haproxy.cfg.j2
  roles/infra/tasks/main.yml
  roles/jenkins/tasks/main.yml
  roles/ldap/tasks/main.yml
  roles/monitoring/files/grafana/provisioning/dashboards/traefik.json
  roles/monitoring/tasks/main.yml
  roles/monitoring/templates/prometheus.yml.j2
  roles/network/tasks/main.yml
  roles/network/templates/traefik.toml.j2
  roles/sonarqube/tasks/main.yml
  roles/utils/tasks/main.yml
Labels: enhancement

#89 dropped bridge network for backend containers
  roles/gitlab/tasks/main.yml
  roles/jenkins/tasks/main.yml
  roles/ldap/tasks/main.yml
  roles/monitoring/tasks/main.yml
  roles/sonarqube/tasks/main.yml
  roles/utils/tasks/main.yml
Labels: bug

#95 fixed dashboards + cadvisors permissions issues on centos
  roles/monitoring/files/grafana/provisioning/dashboards/cadvisor.json
  roles/monitoring/files/grafana/provisioning/dashboards/node_exporter.json
  roles/monitoring/files/grafana/provisioning/dashboards/system.json
  roles/monitoring/tasks/main.yml
Labels: bug

#97 Misc/makefile lint rule
  .circleci/config.yml
  .circleci/lint.sh
  Makefile
Labels: enhancement

#102 Feature/ssl certificates import
  docs/nav/configuration.md
  group_vars/all.yml
  roles/haproxy/tasks/certificates.yml
  roles/haproxy/tasks/main.yml
  roles/haproxy/tasks/selfsign_domain.yml
  roles/haproxy/templates/haproxy.cfg.j2
Labels: enhancement

#91 Update CircleCI config to test ansible playbook
  .circleci/config.yml
Labels: enhancement, good first issue

#109 Fix Configuration for Mkdocs
  mkdocs.yml
Labels: bug

#104 Hotfix/backup restore
  backup.yml
  restore.yml
  roles/backup/tasks/main.yml
Labels: bug

#105 disable anonymous access grafana
  roles/monitoring/files/grafana/config.monitoring
Labels: security
