Repository actiniumio/allspark, pull requests merged in 2018-10, with the labels that each got.

#110 Vagrantfile - Increment Variable
  Vagrantfile
Labels: enhancement

#111 Segregated database network
  roles/utils/tasks/main.yml
Labels: enhancement, security

#117 Hotfix/circleci
  .circleci/config.yml
Labels: bug

#119 Feature/jenkins security
  roles/download/defaults/main.yml
  roles/jenkins/files/master.groovy.d/05.system.groovy
  roles/jenkins/files/master.groovy.d/10.users.groovy
  roles/jenkins/files/master.groovy.d/11.executors.groovy
  roles/jenkins/files/master.groovy.d/12.roles.groovy
  roles/jenkins/files/master.groovy.d/20.security.groovy
  roles/jenkins/files/master.groovy.d/21.csrf.groovy
  roles/jenkins/files/master.groovy.d/90.stats.groovy
  roles/jenkins/files/slave_init.sh
  roles/jenkins/tasks/main.yml
  roles/jenkins/templates/jenkins_security.groovy.j2
Labels: enhancement, security

#121 Feature/benchsecu
  .circleci/config.yml
Labels: enhancement, security

#126 Fix righ pb
  install.yml
  roles/haproxy/tasks/main.yml
  roles/monitoring/tasks/main.yml
  roles/pip/tasks/main.yml
  roles/utils/tasks/main.yml
Labels: bug

#128 Backup & Restore
  roles/backup/defaults/main.yml
  roles/backup/tasks/main.yml
  roles/local_datas/tasks/main.yml
Labels: enhancement

#129 Pyup/scheduled update 2018 10 14
  .circleci/requirements.txt
  roles/haproxy/tasks/selfsign_domain.yml
Labels: enhancement

#136 Hotfix/gitlab migration
  roles/gitlab/handlers/main.yml
  roles/gitlab/tasks/main.yml
Labels: bug, enhancement

#137 hotfix(removed_duplicate_volumerize_conf)
  group_vars/all.yml
Labels: bug

#134 Gitlab runners integration
  roles/gitlab/files/start_runner.sh
  roles/gitlab/tasks/main.yml
  roles/gitlab/tasks/runner.yml
Labels: enhancement

#130 Placeholder receiver for alertmanager
  roles/monitoring/templates/alertmanager.yml.j2
Labels: bug
