Repository actiniumio/allspark, pull requests merged in 2018-07, with the labels that each got.

#26 Integrated a Makefile
  .gitignore
  .travis/deploy_docs.sh
  CONTRIBUTING.md
  Makefile
Labels: enhancement

#30 Feature/pyup bot integration
  .pyup.yml
  README.md
  docs/pages/index.md
Labels: enhancement, security

#28 Hotfix/docs make not executed
  .travis.yml
  .travis/deploy_docs.sh
Labels: bug

#33 stale bot configuration
  .travis/stale.yml
Labels: enhancement

#32 Github templates
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#34 Feature/download role
  CONTRIBUTING.md
  docs/pages/install.md
  group_vars/all.yml
  install.yml
  release.yml
  roles/download/defaults/main.yml
  roles/download/tasks/download_image.yml
  roles/download/tasks/main.yml
  roles/gitlab/tasks/main.yml
  roles/jenkins/tasks/main.yml
  roles/ldap/tasks/main.yml
  roles/monitoring/tasks/main.yml
  roles/network/tasks/main.yml
  roles/sonarqube/tasks/main.yml
  roles/utils/tasks/main.yml
  setup.yml
Labels: enhancement

#41 moved stale config to .github
  .github/stale.yml
Labels: bug

#21 Backup Playbook
  backup.yml
  docs/pages/install.md
  docs/pages/operation.md
  group_vars/all.yml
  mkdocs.yml
  restore.yml
  roles/backup/defaults/main.yml
  roles/backup/tasks/main.yml
  roles/gitlab/tasks/main.yml
  roles/jenkins/tasks/main.yml
  roles/monitoring/tasks/main.yml
  roles/sonarqube/tasks/main.yml
  roles/utils/tasks/main.yml
Labels: enhancement

#42 Feature/makefile rule docs dev
  CONTRIBUTING.md
  Makefile
Labels: enhancement
