Repository actiniumio/allspark, pull requests merged in 2018-08, with the labels that each got.

#47 Hotfix TOC Documentation Operation.md
  docs/pages/operation.md
Labels: bug

#46 Disable --no-auth option and activate --admin-password-file
  roles/local_datas/tasks/main.yml
  roles/utils/tasks/main.yml
Labels: enhancement, security

#52 Improved templates documentation
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#61 Hotfix/replace travis by circle ci
  .circleci/deploy-ghpages.sh
  .travis.yml
  .travis/github_deploy_key.enc
  README.md
  circle.yml
  docs/pages/index.md
Labels: bug, enhancement

#58 Hotfix/yum module
  docs/pages/install.md
  group_vars/all.yml
  roles/system/tasks/rhel7.yml
Labels: enhancement

#48 Update Troubleshoot
  docs/pages/troubleshooting.md
Labels: enhancement

#57 Hotfix/pip module
  install.yml
  roles/pip/files/requirements.txt
  roles/pip/tasks/main.yml
  roles/system/tasks/main.yml
Labels: enhancement

#68 Hotfix/mattermost indepotence
  Makefile
  roles/utils/tasks/main.yml
  roles/utils/templates/config.json.j2
Labels: bug

#72 Feature/ansible lint circleci
  .circleci/.ansible-lint
  .circleci/config.yml
  .circleci/requirements.txt
  CONTRIBUTING.md
  backup.yml
  circle.yml
  release.yml
  restore.yml
  roles/pip/tasks/main.yml
  roles/system/tasks/rhel7.yml
Labels: enhancement, good first issue

#77 Update SSH-Key to build docs
  .circleci/config.yml
Labels: bug

#79 Fix error display on CONTRIBUTING
  CONTRIBUTING.md
Labels: bug

#81 Update Email address on circle config
  .circleci/config.yml
Labels: enhancement
